### ISSUE TITLE
Refactor to DRF-based views

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-widget-framework#10]
The views should be refactored to DRF-based views and accept a configurable `permission_classes` via `django.conf.settings`

**Comment by jklingen92** [comment]
I'm going to do this by implementing ModelViewSets as suggested by @rhysyngsun in the slack. This will simplify the views file and allow us to plug in Django Object Permissions relatively simply.

**Comment by jklingen92** [comment]
@rhysyngsun I just pushed version 0.2.0 for the backend which moves everything to ModelViewSets, implements a proper settings module, and provides settings for authentication and permission classes. These are empty by default but I've tested with DRF's BasicAuthentication class and DjangoObjectPermissions. There is a third setting called WIDGET_LIST_EDIT_PERMISSIONS which is a list of permissions required to make changes to a widget list. These are checked at the object level when you attempt to male changes to a widget list.

Also notable in this commit are changes to the serializer structure. Widget classes now extend WidgetClassBase, and can reference self.data as a usual serializer would.

**Comment by jklingen92** [comment]
@rhysyngsun @aliceriot @pdpinch I also pushed version 0.2.0 (6ca7cb472c205e6773dee0f233a5c628a08713c5) of the frontend which splits the two Widget Form types (for editing vs creating) into two different components. It also changes the request format to better serve the backend drf structure. 

I've seen the pull request you made and I like those changes. There will be some conflicts, so I put my new changes into another branch. I will merge your branch into my branch and once the conflicts are ironed out, if you're on board, I'll merge everything into master.
