### ISSUE TITLE
use yarn for JS packages

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-widget-framework#13]
we tend to use the yarn package manager for managing npm dependencies in our other projects, it would be good to use that here as well, so we're standardized across our repos.

**Comment by jklingen92** [comment]
I ran `yarn` in the framework and it generated a yarn.lock file. Is that all I need to do?

**Comment by aliceriot** [comment]
Yeah, the `yarn.lock` file is a manifest of resolved versions for all the dependencies. Best practice is to commit that file, so that anyone who is developing on the project is always working with the same versions of everything.

**Comment by jklingen92** [comment]
Will do
