### ISSUE TITLE
RSS Feed widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-widget-framework#16]
As.a developer, I'd like a sample widget for managing an RSS feed. 

The configuration would include a title and a URL. The rendered widget would have a list of RSS feed entries with thumbnail, title and link.

**Comment by kyfantaz** [comment]
@pdpinch re: thumbnail, I don't believe there is common RSS standard for conveying image links. So far, I've been testing RSS feeds off of Reddit and NYT, and I believe they send over media links, if any, in a structured way but differently from each other. If media is being sent over in an unstructured way i.e. an image buried in HTML content, I imagine that leaves us with the option of parsing for `img` tag with an `src` attribute for an image url. 

What are the common RSS feeds that you expect the widget to source from? I can look at those to look at specific sources to propose a best option.

**Comment by kyfantaz** [comment]
Closing this for now with PR #19
