### ISSUE TITLE
sample Member widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-widget-framework#17]
As.a developer, I'd like a sample widget for managing lists of users.

The configuration would include a title and a list of user. The rendered widget would display the users.

**Comment by kyfantaz** [comment]
@pdpinch I believe this issue describes our existing ManyUsers widget. We can rename it to be a Members widget, or build off of it to create a new Members widget.

**Comment by kyfantaz** [comment]
Closing this for now with PR #19
