### ISSUE TITLE
Loosen python dependencies

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-widget-framework#6]
Some of the python dependencies are fixed on specific versions which will impede downsteam apps from upgrading to newer versions. These should instead cover some supported range of versions.

**Comment by jklingen92** [comment]
@rhysyngsun We changed the install requires to :

["Django>=2.1.2", "djangorestframework>=3", "psycopg2>=2.7"]

Does that address the issue?

**Comment by rhysyngsun** [comment]
@jklingen92 I think that should fix it, yes
