### ISSUE TITLE
Components should accept a configurable fetchFunc so Open can share its fetch implementation

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-widget-framework#8]
Related #7 

Open [defines its own fetchFunc](https://github.com/mitodl/open-discussions/blob/5bb624e6ff78aaf438f120f4851febb1f9a64d08/static/js/lib/fetch_auth.js#L43) that handles auth failures and other common request functionality. We want to be able to pass that to the widget components.

An example usage of this implementation is here: https://github.com/mitodl/open-discussions/blob/21fb1381a88de57e0104e2b1e3be6f72ad388ebc/static/js/lib/api.js#L200-L213

**Comment by jklingen92** [comment]
@rhysyngsun The fetchData function that you pass into userSettings now has the same inputs as fetch / your fetch wrapper. Let me know if this works. This is up to date in @zagaran/open-widget-framework version 0.1.19

**Comment by jklingen92** [comment]
I figured it out. I didn't realize fetch accepts relative paths. Version 0.1.21 removes all siteBaseUrl references, as well as csrfToken from the settings.
