### ISSUE TITLE
use material-icons for UI elements instead of Octicons

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-widget-framework#9]
this is kind of a question for @pdpinch - we're using `material-icons` everywhere else for discussions, wondering if we want to make sure we're using that here too.

**Comment by aliceriot** [comment]
if we want to go this route I don't _think_ that `open-widget-framework` would need to depend on anything new. the material-icons icon list is here: https://material.io/icons

to use one you do something like this (for instance to use the `'pencil'` icon):

```js
<i className="material-icons pencil">pencil</i>
```

and the rest should be taken care of in open-discussions, where we get the material-icons stuff from Google's CDN.

**Comment by pdpinch** [comment]
Yes, we should use material-icons.

**Comment by pdpinch** [comment]
On second thought, this is premature because we haven't got final designs yet. Even if the icons will be material, it's not worth changing them yet.
